#include <QtTest>
#include <QJsonObject>
#include <QDir>
#include <QFile>
#include <QFileInfo>
#include <QCoreApplication>
#include "core/ChecklistEngine.h"
#include "core/ExportService.h"
#include "core/SurveyProjectFactory.h"
#include "core/ProjectStateBuilder.h"
#include "core/LayoutService.h"

#include <qgsapplication.h>
#include <qgsproject.h>
#include <qgscoordinatereferencesystem.h>
#include <qgsvectorlayer.h>
#include <qgsrectangle.h>
#include <qgsprintlayout.h>
#include <qgslayoutitemmap.h>
#include <qgslayoutmanager.h>
#include <qgsmaplayer.h>
#include <qgsgeometry.h>
#include <qgsfeature.h>
#include <qgspointxy.h>
#include <qgsrasterlayer.h>
#include "core/LayerOps.h"
#include <QTemporaryDir>
#include <limits>

class TestKaHgis : public QObject {
  Q_OBJECT
private slots:
  void initTestCase();
  void cleanupTestCase();
  void loadRules();
  void evaluateFailsWithoutSurvey();
  void evaluatePassesHappyFixture();
  void exportBlocksOnError();
  void exportAllowsWhenClean();
  void pdfViaLayout();
  void surveyCreatesGpkg();
  void liveStateFromEmptyProject();
  void fromProject_emptySeededSiteLocation_layoutExistsFalse();
  void fromProject_composedUserSheet_layoutExistsTrue();
  void test_uncomposed_user_sheet_rejected();
  void test_dummy_blank_layer_rejected();
  void test_autogenerated_template_not_passing_feature_plan();

  // Adversarial Challenge M1-1 Probes
  void challenge1_isComposed_emptyVectorAndRaster();
  void challenge2_isComposed_basemapCombinations();
  void challenge3_isComposed_zeroAreaPolygon();
  void challenge4_isComposed_nanInfExtentsNegativeScales();
  void challenge5_isComposed_customNamedLayoutsAndMultipleMaps();
  void challenge6_projectState_featurePlanWithoutActualFeatures();
  void challenge7_projectState_siteLocationWithoutSurveyArea();
  void challenge8_isComposed_autoGeneratedTemplateBypass();
private:
  QgsApplication* m_app = nullptr;
};

static QString rulesFile() {
  const QStringList c = {
    QDir::current().filePath(QStringLiteral("data/rules/drawing_checklist.v1.json")),
    QDir(QCoreApplication::applicationDirPath()).filePath(QStringLiteral("data/rules/drawing_checklist.v1.json")),
    QDir(QCoreApplication::applicationDirPath()).filePath(QStringLiteral("../data/rules/drawing_checklist.v1.json")),
    QDir(QCoreApplication::applicationDirPath()).filePath(QStringLiteral("../../data/rules/drawing_checklist.v1.json")),
  };
  for (const auto& p : c) if (QFile::exists(p)) return p;
  return c.first();
}

void TestKaHgis::initTestCase() {
  // QgsApplication already constructed by QTEST_MAIN via QCoreApplication - use existing
}

void TestKaHgis::cleanupTestCase() {}

void TestKaHgis::loadRules() {
  ChecklistEngine e;
  QVERIFY2(e.loadRules(rulesFile()), qPrintable(rulesFile()));
  QVERIFY(e.ruleCount() >= 12);
}

void TestKaHgis::evaluateFailsWithoutSurvey() {
  ChecklistEngine e;
  QVERIFY(e.loadRules(rulesFile()));
  QJsonObject st = ProjectStateBuilder::empty();
  const auto r = e.evaluate(st);
  int errors = 0;
  for (const auto& x : r) if (!x.passed && x.severity == QLatin1String("error")) errors++;
  QVERIFY2(errors >= 1, "expected checklist errors on empty project");
}

void TestKaHgis::evaluatePassesHappyFixture() {
  ChecklistEngine e;
  QVERIFY(e.loadRules(rulesFile()));
  QJsonObject st;
  st.insert(QStringLiteral("survey_area_count"), 1);
  st.insert(QStringLiteral("control_points_count"), 2);
  st.insert(QStringLiteral("project_crs_set"), true);
  st.insert(QStringLiteral("has_datum"), true);
  st.insert(QStringLiteral("has_ellipsoid"), true);
  st.insert(QStringLiteral("has_projection"), true);
  st.insert(QStringLiteral("has_origin"), true);
  st.insert(QStringLiteral("has_accuracy"), true);
  st.insert(QStringLiteral("has_abstract_marker"), false);
  st.insert(QStringLiteral("survey_is_polygon"), true);
  st.insert(QStringLiteral("feature_poly_count"), 1);
  st.insert(QStringLiteral("has_kind_period"), true);
  st.insert(QStringLiteral("features_within_survey"), true);
  st.insert(QStringLiteral("geometries_valid"), true);
  st.insert(QStringLiteral("layout_exists:site_location"), true);
  st.insert(QStringLiteral("layout_exists:feature_plan"), true);
  st.insert(QStringLiteral("layout_exists:feature_detail"), true);
  st.insert(QStringLiteral("layout_exists:section"), true);
  const auto r = e.evaluate(st);
  int errors = 0;
  for (const auto& x : r) if (!x.passed && x.severity == QLatin1String("error")) errors++;
  QCOMPARE(errors, 0);
}

void TestKaHgis::exportBlocksOnError() {
  // API still supports blocking when caller passes blockOnError=true.
  // Phase-1 MainWindow passes false (tool export, not gate).
  QString err;
  const QString out = ExportService::exportSubmissionPackage(
      nullptr, QDir::temp().filePath(QStringLiteral("ka_block")), QStringLiteral("UTF-8"),
      QStringLiteral("fail"), true, true, &err);
  QVERIFY(out.isEmpty());
  QVERIFY(!err.isEmpty());
}

void TestKaHgis::exportAllowsWhenClean() {
  const QString dir = QDir::temp().filePath(QStringLiteral("ka_ok_pkg"));
  QDir(dir).removeRecursively();
  QString err;
  // Phase-1 path: blockOnError=false even if hasChecklistErrors (errors only in README).
  const QString outDirty = ExportService::exportSubmissionPackage(
      nullptr, dir + QStringLiteral("_dirty"), QStringLiteral("UTF-8"),
      QStringLiteral("- [error] demo\n"), false, true, &err);
  QVERIFY2(!outDirty.isEmpty(), qPrintable(err));
  QVERIFY(QFile::exists(QDir(dir + QStringLiteral("_dirty")).filePath(QStringLiteral("README_submit.txt"))));

  err.clear();
  const QString out = ExportService::exportSubmissionPackage(
      nullptr, dir, QStringLiteral("UTF-8"), QStringLiteral("OK"), true, false, &err);
  QVERIFY2(!out.isEmpty(), qPrintable(err));
  QVERIFY(QFile::exists(QDir(dir).filePath(QStringLiteral("README_submit.txt"))));
  QVERIFY(QFile::exists(QDir(dir).filePath(QStringLiteral("MANIFEST.sha256"))));
}

void TestKaHgis::pdfViaLayout() {
  QgsProject proj;
  proj.setCrs(QgsCoordinateReferenceSystem(QStringLiteral("EPSG:5179")));
  LayoutService::ensureDefaultLayouts(&proj);
  QCOMPARE(LayoutService::defaultLayoutNames().size(), 5);
  const QString p = QDir::temp().filePath(QStringLiteral("ka_layout_test.pdf"));
  QFile::remove(p);
  QString err;
  const QString out = ExportService::writePdfViaLayout(&proj, QStringLiteral("feature_plan"), p, &err);
  QVERIFY2(!out.isEmpty(), qPrintable(err));
  QVERIFY(QFileInfo(p).size() > 500);
}

void TestKaHgis::surveyCreatesGpkg() {
  const QString dir = QDir::temp().filePath(QStringLiteral("ka_survey_gpkg"));
  QDir(dir).removeRecursively();
  QDir().mkpath(dir);
  QString err;
  const QString path = SurveyProjectFactory::createNewSurvey(dir, QStringLiteral("demo"), &err);
  QVERIFY2(!path.isEmpty(), qPrintable(err));
  QVERIFY(QFile::exists(path));
}

void TestKaHgis::liveStateFromEmptyProject() {
  QgsProject proj;
  const QJsonObject st = ProjectStateBuilder::fromProject(&proj);
  QCOMPARE(st.value(QStringLiteral("survey_area_count")).toInt(), 0);
  QVERIFY(st.contains(QStringLiteral("project_crs_set")));
}

void TestKaHgis::fromProject_emptySeededSiteLocation_layoutExistsFalse() {
  QgsProject proj;
  proj.setCrs(QgsCoordinateReferenceSystem(QStringLiteral("EPSG:5186")));
  LayoutService::ensureDefaultLayouts(&proj);
  QVERIFY(proj.layoutManager()->layoutByName(QStringLiteral("site_location")));
  QVERIFY(proj.layoutManager()->layoutByName(QStringLiteral("feature_plan")));
  const QJsonObject st = ProjectStateBuilder::fromProject(&proj);
  QVERIFY(!st.value(QStringLiteral("layout_exists:site_location")).toBool());
  QVERIFY(!st.value(QStringLiteral("layout_exists:feature_plan")).toBool());
  QVERIFY(!st.value(QStringLiteral("layout_exists:survey_area_map")).toBool());
  QVERIFY(!st.value(QStringLiteral("layout_exists:feature_detail")).toBool());
  QVERIFY(!st.value(QStringLiteral("layout_exists:section")).toBool());
}

void TestKaHgis::fromProject_composedUserSheet_layoutExistsTrue() {
  QgsProject proj;
  proj.setCrs(QgsCoordinateReferenceSystem(QStringLiteral("EPSG:5186")));

  // 1. Create genuine survey_area layer with 1 polygon feature
  auto* sa = new QgsVectorLayer(QStringLiteral("Polygon?crs=EPSG:5186"),
                                QStringLiteral("survey_area"), QStringLiteral("memory"));
  QVERIFY(sa->isValid());
  sa->setCustomProperty(QStringLiteral("ka_hgis/layer_key"), QStringLiteral("survey_area"));
  proj.addMapLayer(sa);

  QVERIFY(sa->startEditing());
  QgsFeature sf(sa->fields());
  QgsPolylineXY ring;
  ring << QgsPointXY(200000.0, 450000.0)
       << QgsPointXY(200200.0, 450000.0)
       << QgsPointXY(200200.0, 450160.0)
       << QgsPointXY(200000.0, 450160.0)
       << QgsPointXY(200000.0, 450000.0);
  sf.setGeometry(QgsGeometry::fromPolygonXY(QgsPolygonXY() << ring));
  QVERIFY(sa->addFeature(sf));
  QVERIFY(sa->commitChanges());
  QCOMPARE(sa->featureCount(), 1);

  // 2. Create genuine feature_poly layer with 1 polygon feature
  auto* fp = new QgsVectorLayer(QStringLiteral("Polygon?crs=EPSG:5186"),
                                QStringLiteral("feature_poly"), QStringLiteral("memory"));
  QVERIFY(fp->isValid());
  fp->setCustomProperty(QStringLiteral("ka_hgis/layer_key"), QStringLiteral("feature_poly"));
  proj.addMapLayer(fp);

  QVERIFY(fp->startEditing());
  QgsFeature ff(fp->fields());
  QgsPolylineXY fring;
  fring << QgsPointXY(200050.0, 450050.0)
        << QgsPointXY(200080.0, 450050.0)
        << QgsPointXY(200080.0, 450080.0)
        << QgsPointXY(200050.0, 450080.0)
        << QgsPointXY(200050.0, 450050.0);
  ff.setGeometry(QgsGeometry::fromPolygonXY(QgsPolygonXY() << fring));
  QVERIFY(fp->addFeature(ff));
  QVERIFY(fp->commitChanges());
  QCOMPARE(fp->featureCount(), 1);

  // 3. Compose user_sheet layout with ka_map referencing real layers
  QString err;
  QVERIFY(!LayoutService::createBlankSheet(&proj, 297.0, 210.0, QStringLiteral("user_sheet"), &err).isEmpty());
  auto* ly = dynamic_cast<QgsPrintLayout*>(proj.layoutManager()->layoutByName(QStringLiteral("user_sheet")));
  QVERIFY2(ly, qPrintable(err));

  auto* map = new QgsLayoutItemMap(ly);
  map->setId(QStringLiteral("ka_map"));
  map->attemptSetSceneRect(QRectF(20.0, 20.0, 120.0, 80.0));
  map->setCrs(QgsCoordinateReferenceSystem(QStringLiteral("EPSG:5186")));
  map->setKeepLayerSet(true);
  map->setLayers(QList<QgsMapLayer*>{sa, fp});
  map->zoomToExtent(QgsRectangle(200000.0, 450000.0, 200200.0, 450160.0));
  if (map->scene() != ly)
    ly->addLayoutItem(map);

  // 4. Verify composition passes
  QVERIFY(LayoutService::isComposedStudioSheet(&proj));

  // 5. Verify checklist flags in live project state
  const QJsonObject st = ProjectStateBuilder::fromProject(&proj);
  QCOMPARE(st.value(QStringLiteral("survey_area_count")).toInt(), 1);
  QCOMPARE(st.value(QStringLiteral("feature_poly_count")).toInt(), 1);
  QVERIFY(st.value(QStringLiteral("layout_exists:site_location")).toBool());
  QVERIFY(st.value(QStringLiteral("layout_exists:feature_plan")).toBool());
  QVERIFY(st.value(QStringLiteral("layout_exists:survey_area_map")).toBool());
  QVERIFY(!st.value(QStringLiteral("layout_exists:section")).toBool());
  QVERIFY(!st.value(QStringLiteral("layout_exists:feature_detail")).toBool());
}

void TestKaHgis::test_uncomposed_user_sheet_rejected() {
  QgsProject proj;
  proj.setCrs(QgsCoordinateReferenceSystem(QStringLiteral("EPSG:5186")));

  // Survey area exists in project
  auto* sa = new QgsVectorLayer(QStringLiteral("Polygon?crs=EPSG:5186"),
                                QStringLiteral("survey_area"), QStringLiteral("memory"));
  QVERIFY(sa->isValid());
  sa->setCustomProperty(QStringLiteral("ka_hgis/layer_key"), QStringLiteral("survey_area"));
  proj.addMapLayer(sa);
  QVERIFY(sa->startEditing());
  QgsFeature sf(sa->fields());
  QgsPolylineXY ring;
  ring << QgsPointXY(200000.0, 450000.0) << QgsPointXY(200100.0, 450000.0)
       << QgsPointXY(200100.0, 450100.0) << QgsPointXY(200000.0, 450100.0)
       << QgsPointXY(200000.0, 450000.0);
  sf.setGeometry(QgsGeometry::fromPolygonXY(QgsPolygonXY() << ring));
  QVERIFY(sa->addFeature(sf));
  QVERIFY(sa->commitChanges());

  // Scenario A: Blank user_sheet created, NO map item added
  QString err;
  QVERIFY(!LayoutService::createBlankSheet(&proj, 297.0, 210.0, QStringLiteral("user_sheet"), &err).isEmpty());
  QVERIFY2(!LayoutService::isComposedStudioSheet(&proj), "Blank sheet without map must be rejected");

  QJsonObject st = ProjectStateBuilder::fromProject(&proj);
  QVERIFY2(!st.value(QStringLiteral("layout_exists:site_location")).toBool(), "Uncomposed sheet must not satisfy site_location");
  QVERIFY2(!st.value(QStringLiteral("layout_exists:feature_plan")).toBool(), "Uncomposed sheet must not satisfy feature_plan");
  QVERIFY2(!st.value(QStringLiteral("layout_exists:survey_area_map")).toBool(), "Uncomposed sheet must not satisfy survey_area_map");

  // Checklist evaluation must fail REQ_DRAWING_SITE_LOCATION and REQ_DRAWING_FEATURE_PLAN
  ChecklistEngine engine;
  QVERIFY(engine.loadRules(rulesFile()));
  const auto results = engine.evaluate(st);
  bool siteLocFailed = false;
  bool featPlanFailed = false;
  for (const auto& r : results) {
    if (r.id == QLatin1String("REQ_DRAWING_SITE_LOCATION") && !r.passed) siteLocFailed = true;
    if (r.id == QLatin1String("REQ_DRAWING_FEATURE_PLAN") && !r.passed) featPlanFailed = true;
  }
  QVERIFY2(siteLocFailed, "REQ_DRAWING_SITE_LOCATION must fail for uncomposed sheet");
  QVERIFY2(featPlanFailed, "REQ_DRAWING_FEATURE_PLAN must fail for uncomposed sheet");

  // Scenario B: Map item added but has no layers assigned
  auto* ly = dynamic_cast<QgsPrintLayout*>(proj.layoutManager()->layoutByName(QStringLiteral("user_sheet")));
  QVERIFY(ly);
  auto* map = new QgsLayoutItemMap(ly);
  map->setId(QStringLiteral("ka_map"));
  map->attemptSetSceneRect(QRectF(20.0, 20.0, 120.0, 80.0));
  map->setCrs(QgsCoordinateReferenceSystem(QStringLiteral("EPSG:5186")));
  map->setKeepLayerSet(true);
  map->setLayers({}); // empty layers
  ly->addLayoutItem(map);

  QVERIFY2(!LayoutService::isComposedStudioSheet(&proj), "Map item with empty layers must be rejected");
}

void TestKaHgis::test_dummy_blank_layer_rejected() {
  QgsProject proj;
  proj.setCrs(QgsCoordinateReferenceSystem(QStringLiteral("EPSG:5186")));

  // 1. Add placeholder layout_blank layer with 0 features
  auto* blank = new QgsVectorLayer(QStringLiteral("Polygon?crs=EPSG:5186"),
                                   QStringLiteral("layout_blank"), QStringLiteral("memory"));
  QVERIFY(blank->isValid());
  proj.addMapLayer(blank);
  QCOMPARE(blank->featureCount(), 0);

  QString err;
  QVERIFY(!LayoutService::createBlankSheet(&proj, 297.0, 210.0, QStringLiteral("user_sheet"), &err).isEmpty());
  auto* ly = dynamic_cast<QgsPrintLayout*>(proj.layoutManager()->layoutByName(QStringLiteral("user_sheet")));
  QVERIFY(ly);

  auto* map = new QgsLayoutItemMap(ly);
  map->setId(QStringLiteral("ka_map"));
  map->attemptSetSceneRect(QRectF(20.0, 20.0, 120.0, 80.0));
  map->setCrs(QgsCoordinateReferenceSystem(QStringLiteral("EPSG:5186")));
  map->setKeepLayerSet(true);
  map->setLayers(QList<QgsMapLayer*>{blank});
  map->zoomToExtent(QgsRectangle(200000.0, 450000.0, 200200.0, 450160.0));
  ly->addLayoutItem(map);

  // Map exists, scale > 0, but layer is layout_blank with 0 features -> MUST REJECT
  QVERIFY2(!LayoutService::isComposedStudioSheet(&proj),
           "layout_blank with 0 features must be rejected by isComposedStudioSheet");

  const QJsonObject st = ProjectStateBuilder::fromProject(&proj);
  QVERIFY2(!st.value(QStringLiteral("layout_exists:site_location")).toBool(),
           "layout_blank must not satisfy site_location");
  QVERIFY2(!st.value(QStringLiteral("layout_exists:feature_plan")).toBool(),
           "layout_blank must not satisfy feature_plan");

  // 2. Test another memory layer with 0 features
  auto* emptyVector = new QgsVectorLayer(QStringLiteral("Polygon?crs=EPSG:5186"),
                                         QStringLiteral("empty_survey"), QStringLiteral("memory"));
  QVERIFY(emptyVector->isValid());
  proj.addMapLayer(emptyVector);
  map->setLayers(QList<QgsMapLayer*>{emptyVector});

  QVERIFY2(!LayoutService::isComposedStudioSheet(&proj),
           "Zero-feature vector layer must be rejected by isComposedStudioSheet");
}

void TestKaHgis::test_autogenerated_template_not_passing_feature_plan() {
  QgsProject proj;
  proj.setCrs(QgsCoordinateReferenceSystem(QStringLiteral("EPSG:5186")));

  // Add survey_area layer with 1 polygon feature
  auto* sa = new QgsVectorLayer(QStringLiteral("Polygon?crs=EPSG:5186"),
                                QStringLiteral("survey_area"), QStringLiteral("memory"));
  QVERIFY(sa->isValid());
  sa->setCustomProperty(QStringLiteral("ka_hgis/layer_key"), QStringLiteral("survey_area"));
  proj.addMapLayer(sa);
  QVERIFY(sa->startEditing());
  QgsFeature sf(sa->fields());
  QgsPolylineXY ring;
  ring << QgsPointXY(200000.0, 450000.0) << QgsPointXY(200100.0, 450000.0)
       << QgsPointXY(200100.0, 450100.0) << QgsPointXY(200000.0, 450100.0)
       << QgsPointXY(200000.0, 450000.0);
  sf.setGeometry(QgsGeometry::fromPolygonXY(QgsPolygonXY() << ring));
  QVERIFY(sa->addFeature(sf));
  QVERIFY(sa->commitChanges());

  // Explicitly verify NO feature_poly or feature_line exists
  QVERIFY(!proj.mapLayersByName(QStringLiteral("feature_poly")).size());
  QVERIFY(!proj.mapLayersByName(QStringLiteral("feature_line")).size());

  // Auto-generate default background templates
  LayoutService::ensureDefaultLayouts(&proj);
  QVERIFY(proj.layoutManager()->layoutByName(QStringLiteral("feature_plan")));

  const QJsonObject st = ProjectStateBuilder::fromProject(&proj);
  QCOMPARE(st.value(QStringLiteral("survey_area_count")).toInt(), 1);
  QCOMPARE(st.value(QStringLiteral("feature_poly_count")).toInt(), 0);
  QCOMPARE(st.value(QStringLiteral("feature_line_count")).toInt(), 0);

  // Crucial check: Auto-generated feature_plan template MUST NOT pass when feature count is 0
  QVERIFY2(!st.value(QStringLiteral("layout_exists:feature_plan")).toBool(),
           "Auto-generated template must not satisfy feature_plan without actual features");

  // Verify ChecklistEngine flags REQ_DRAWING_FEATURE_PLAN as failed
  ChecklistEngine engine;
  QVERIFY(engine.loadRules(rulesFile()));
  const auto results = engine.evaluate(st);
  bool featurePlanFailed = false;
  for (const auto& r : results) {
    if (r.id == QLatin1String("REQ_DRAWING_FEATURE_PLAN")) {
      featurePlanFailed = !r.passed;
      QCOMPARE(r.severity, QStringLiteral("error"));
    }
  }
  QVERIFY2(featurePlanFailed, "REQ_DRAWING_FEATURE_PLAN must report error");
}

void TestKaHgis::challenge1_isComposed_emptyVectorAndRaster() {
  QgsProject proj;
  proj.setCrs(QgsCoordinateReferenceSystem(QStringLiteral("EPSG:5186")));

  QString err;
  QVERIFY(!LayoutService::createBlankSheet(&proj, 297.0, 210.0, QStringLiteral("user_sheet"), &err).isEmpty());
  auto* ly = dynamic_cast<QgsPrintLayout*>(proj.layoutManager()->layoutByName(QStringLiteral("user_sheet")));
  QVERIFY(ly);

  auto* map = new QgsLayoutItemMap(ly);
  map->setId(QStringLiteral("ka_map"));
  map->attemptSetSceneRect(QRectF(20.0, 20.0, 120.0, 80.0));
  map->setCrs(QgsCoordinateReferenceSystem(QStringLiteral("EPSG:5186")));
  map->setKeepLayerSet(true);
  map->zoomToExtent(QgsRectangle(200000.0, 450000.0, 200200.0, 450160.0));
  map->setScale(1000.0);
  ly->addLayoutItem(map);

  // 1A. Empty LineString vector layer
  auto* emptyLine = new QgsVectorLayer(QStringLiteral("LineString?crs=EPSG:5186"), QStringLiteral("empty_line"), QStringLiteral("memory"));
  QVERIFY(emptyLine->isValid());
  proj.addMapLayer(emptyLine);
  map->setLayers(QList<QgsMapLayer*>{emptyLine});
  QVERIFY2(!LayoutService::isComposedStudioSheet(&proj), "Empty LineString layer must be rejected");

  // 1B. Empty Point vector layer
  auto* emptyPoint = new QgsVectorLayer(QStringLiteral("Point?crs=EPSG:5186"), QStringLiteral("empty_pt"), QStringLiteral("memory"));
  QVERIFY(emptyPoint->isValid());
  proj.addMapLayer(emptyPoint);
  map->setLayers(QList<QgsMapLayer*>{emptyPoint});
  QVERIFY2(!LayoutService::isComposedStudioSheet(&proj), "Empty Point layer must be rejected");

  // 1C. Null map layer in list
  map->setLayers(QList<QgsMapLayer*>{nullptr});
  QVERIFY2(!LayoutService::isComposedStudioSheet(&proj), "Null map layer in list must not crash and must be rejected");
}

void TestKaHgis::challenge2_isComposed_basemapCombinations() {
  QgsProject proj;
  proj.setCrs(QgsCoordinateReferenceSystem(QStringLiteral("EPSG:5186")));

  QString err;
  QVERIFY(!LayoutService::createBlankSheet(&proj, 297.0, 210.0, QStringLiteral("user_sheet"), &err).isEmpty());
  auto* ly = dynamic_cast<QgsPrintLayout*>(proj.layoutManager()->layoutByName(QStringLiteral("user_sheet")));
  QVERIFY(ly);

  auto* map = new QgsLayoutItemMap(ly);
  map->setId(QStringLiteral("ka_map"));
  map->attemptSetSceneRect(QRectF(20.0, 20.0, 120.0, 80.0));
  map->setCrs(QgsCoordinateReferenceSystem(QStringLiteral("EPSG:5186")));
  map->setKeepLayerSet(true);
  map->zoomToExtent(QgsRectangle(200000.0, 450000.0, 200200.0, 450160.0));
  map->setScale(1000.0);
  ly->addLayoutItem(map);

  // Layer 1: Empty domain vector layer (0 features)
  auto* sa = new QgsVectorLayer(QStringLiteral("Polygon?crs=EPSG:5186"), QStringLiteral("survey_area"), QStringLiteral("memory"));
  sa->setCustomProperty(QStringLiteral("ka_hgis/layer_key"), QStringLiteral("survey_area"));
  proj.addMapLayer(sa);

  // Layer 2: Basemap with "wms" provider or named "VWorld Satellite"
  auto* basemap = new QgsVectorLayer(QStringLiteral("Polygon?crs=EPSG:5186"), QStringLiteral("VWorld Satellite"), QStringLiteral("memory"));
  QVERIFY(basemap->startEditing());
  QgsFeature bf(basemap->fields());
  QgsPolylineXY ring;
  ring << QgsPointXY(199000.0, 449000.0) << QgsPointXY(201000.0, 449000.0)
       << QgsPointXY(201000.0, 451000.0) << QgsPointXY(199000.0, 451000.0)
       << QgsPointXY(199000.0, 449000.0);
  bf.setGeometry(QgsGeometry::fromPolygonXY(QgsPolygonXY() << ring));
  QVERIFY(basemap->addFeature(bf));
  QVERIFY(basemap->commitChanges());
  QCOMPARE(basemap->featureCount(), 1);
  proj.addMapLayer(basemap);

  // Combo: Map contains both survey_area (0 features) and VWorld Satellite (1 feature)
  map->setLayers(QList<QgsMapLayer*>{sa, basemap});

  // Since only basemap has data and survey layer is empty, it MUST BE REJECTED
  const bool composed = LayoutService::isComposedStudioSheet(&proj);
  qDebug() << "[CHALLENGE 2A] Multi-layer with empty survey and VWorld basemap -> isComposed:" << composed;
  QVERIFY2(!composed, "Multi-layer combination where only VWorld basemap has data must be rejected");

  // Sub-probe 2B: Custom reference layer whose name is not caught by hardcoded strings, but marked with role=reference
  auto* customRef = new QgsVectorLayer(QStringLiteral("Polygon?crs=EPSG:5186"), QStringLiteral("custom_ref_dxf"), QStringLiteral("memory"));
  customRef->setCustomProperty(QString::fromUtf8(LayerOps::kPropLayerRole), QString::fromUtf8(LayerOps::kRoleReference));
  QVERIFY(customRef->startEditing());
  QgsFeature rf(customRef->fields());
  rf.setGeometry(QgsGeometry::fromPolygonXY(QgsPolygonXY() << ring));
  QVERIFY(customRef->addFeature(rf));
  QVERIFY(customRef->commitChanges());
  proj.addMapLayer(customRef);

  map->setLayers(QList<QgsMapLayer*>{sa, customRef});
  const bool composedRef = LayoutService::isComposedStudioSheet(&proj);
  qDebug() << "[CHALLENGE 2B] Multi-layer with empty survey and custom reference layer -> isComposed:" << composedRef;
  QVERIFY2(!composedRef, "Multi-layer combination where only custom reference layer has data must be rejected");
}

void TestKaHgis::challenge3_isComposed_zeroAreaPolygon() {
  QgsProject proj;
  proj.setCrs(QgsCoordinateReferenceSystem(QStringLiteral("EPSG:5186")));

  QString err;
  QVERIFY(!LayoutService::createBlankSheet(&proj, 297.0, 210.0, QStringLiteral("user_sheet"), &err).isEmpty());
  auto* ly = dynamic_cast<QgsPrintLayout*>(proj.layoutManager()->layoutByName(QStringLiteral("user_sheet")));
  QVERIFY(ly);

  auto* map = new QgsLayoutItemMap(ly);
  map->setId(QStringLiteral("ka_map"));
  map->attemptSetSceneRect(QRectF(20.0, 20.0, 120.0, 80.0));
  map->setCrs(QgsCoordinateReferenceSystem(QStringLiteral("EPSG:5186")));
  map->setKeepLayerSet(true);
  map->zoomToExtent(QgsRectangle(200000.0, 450000.0, 200200.0, 450160.0));
  map->setScale(1000.0);
  ly->addLayoutItem(map);

  // Probe 3A: Polygon where all 4 vertices are identical (point degenerate, area = 0.0)
  auto* zeroPoly = new QgsVectorLayer(QStringLiteral("Polygon?crs=EPSG:5186"), QStringLiteral("feature_poly"), QStringLiteral("memory"));
  zeroPoly->setCustomProperty(QStringLiteral("ka_hgis/layer_key"), QStringLiteral("feature_poly"));
  QVERIFY(zeroPoly->startEditing());
  QgsFeature f1(zeroPoly->fields());
  QgsPolylineXY degenRing;
  degenRing << QgsPointXY(200100.0, 450050.0) << QgsPointXY(200100.0, 450050.0)
            << QgsPointXY(200100.0, 450050.0) << QgsPointXY(200100.0, 450050.0);
  const QgsGeometry gDegen = QgsGeometry::fromPolygonXY(QgsPolygonXY() << degenRing);
  f1.setGeometry(gDegen);
  QVERIFY(zeroPoly->addFeature(f1));
  QVERIFY(zeroPoly->commitChanges());
  proj.addMapLayer(zeroPoly);
  map->setLayers(QList<QgsMapLayer*>{zeroPoly});

  qDebug() << "[CHALLENGE 3A] Degenerate polygon geometry area:" << gDegen.area() << "isValid:" << gDegen.isGeosValid();
  const bool composed3A = LayoutService::isComposedStudioSheet(&proj);
  qDebug() << "[CHALLENGE 3A] isComposedStudioSheet with zero-area polygon:" << composed3A;

  // Probe 3B: Feature with empty geometry (POLYGON EMPTY)
  auto* emptyGeomLayer = new QgsVectorLayer(QStringLiteral("Polygon?crs=EPSG:5186"), QStringLiteral("empty_geom_poly"), QStringLiteral("memory"));
  QVERIFY(emptyGeomLayer->startEditing());
  QgsFeature fEmpty(emptyGeomLayer->fields());
  fEmpty.setGeometry(QgsGeometry::fromWkt(QStringLiteral("POLYGON EMPTY")));
  QVERIFY(emptyGeomLayer->addFeature(fEmpty));
  QVERIFY(emptyGeomLayer->commitChanges());
  proj.addMapLayer(emptyGeomLayer);
  map->setLayers(QList<QgsMapLayer*>{emptyGeomLayer});

  const bool composed3B = LayoutService::isComposedStudioSheet(&proj);
  qDebug() << "[CHALLENGE 3B] isComposedStudioSheet with POLYGON EMPTY feature:" << composed3B;

  // Probe 3C: Feature with NULL geometry
  auto* nullGeomLayer = new QgsVectorLayer(QStringLiteral("Polygon?crs=EPSG:5186"), QStringLiteral("null_geom_poly"), QStringLiteral("memory"));
  QVERIFY(nullGeomLayer->startEditing());
  QgsFeature fNull(nullGeomLayer->fields());
  fNull.setGeometry(QgsGeometry());
  QVERIFY(nullGeomLayer->addFeature(fNull));
  QVERIFY(nullGeomLayer->commitChanges());
  proj.addMapLayer(nullGeomLayer);
  map->setLayers(QList<QgsMapLayer*>{nullGeomLayer});

  const bool composed3C = LayoutService::isComposedStudioSheet(&proj);
  qDebug() << "[CHALLENGE 3C] isComposedStudioSheet with NULL geometry feature:" << composed3C;
}

void TestKaHgis::challenge4_isComposed_nanInfExtentsNegativeScales() {
  QgsProject proj;
  proj.setCrs(QgsCoordinateReferenceSystem(QStringLiteral("EPSG:5186")));

  QString err;
  QVERIFY(!LayoutService::createBlankSheet(&proj, 297.0, 210.0, QStringLiteral("user_sheet"), &err).isEmpty());
  auto* ly = dynamic_cast<QgsPrintLayout*>(proj.layoutManager()->layoutByName(QStringLiteral("user_sheet")));
  QVERIFY(ly);

  auto* sa = new QgsVectorLayer(QStringLiteral("Polygon?crs=EPSG:5186"), QStringLiteral("survey_area"), QStringLiteral("memory"));
  QVERIFY(sa->startEditing());
  QgsFeature sf(sa->fields());
  QgsPolylineXY ring;
  ring << QgsPointXY(200000.0, 450000.0) << QgsPointXY(200100.0, 450000.0)
       << QgsPointXY(200100.0, 450100.0) << QgsPointXY(200000.0, 450100.0)
       << QgsPointXY(200000.0, 450000.0);
  sf.setGeometry(QgsGeometry::fromPolygonXY(QgsPolygonXY() << ring));
  QVERIFY(sa->addFeature(sf));
  QVERIFY(sa->commitChanges());
  proj.addMapLayer(sa);

  auto* map = new QgsLayoutItemMap(ly);
  map->setId(QStringLiteral("ka_map"));
  map->attemptSetSceneRect(QRectF(20.0, 20.0, 120.0, 80.0));
  map->setCrs(QgsCoordinateReferenceSystem(QStringLiteral("EPSG:5186")));
  map->setKeepLayerSet(true);
  map->setLayers(QList<QgsMapLayer*>{sa});
  ly->addLayoutItem(map);

  // 4A. Negative scale
  map->zoomToExtent(QgsRectangle(200000.0, 450000.0, 200100.0, 450100.0));
  map->setScale(-500.0);
  QVERIFY2(!LayoutService::isComposedStudioSheet(&proj), "Negative scale must be rejected");

  // 4B. Zero scale
  map->setScale(0.0);
  QVERIFY2(!LayoutService::isComposedStudioSheet(&proj), "Zero scale must be rejected");

  // 4C. Infinite scale
  map->setScale(std::numeric_limits<double>::infinity());
  QVERIFY2(!LayoutService::isComposedStudioSheet(&proj), "Infinite scale must be rejected");

  // 4D. NaN scale
  map->setScale(std::numeric_limits<double>::quiet_NaN());
  QVERIFY2(!LayoutService::isComposedStudioSheet(&proj), "NaN scale must be rejected");

  // Reset valid scale
  map->setScale(1000.0);

  // 4E. Zero extent
  map->zoomToExtent(QgsRectangle(0.0, 0.0, 0.0, 0.0));
  QVERIFY2(!LayoutService::isComposedStudioSheet(&proj), "Zero extent must be rejected");

  // 4F. Zero width extent (vertical line)
  map->zoomToExtent(QgsRectangle(200000.0, 450000.0, 200000.0, 450100.0));
  QVERIFY2(!LayoutService::isComposedStudioSheet(&proj), "Zero-width extent must be rejected");

  // 4G. Zero height extent (horizontal line)
  map->zoomToExtent(QgsRectangle(200000.0, 450000.0, 200100.0, 450000.0));
  QVERIFY2(!LayoutService::isComposedStudioSheet(&proj), "Zero-height extent must be rejected");

  // 4H. NaN extent
  map->zoomToExtent(QgsRectangle(std::numeric_limits<double>::quiet_NaN(), 450000.0, 200100.0, 450100.0));
  QVERIFY2(!LayoutService::isComposedStudioSheet(&proj), "NaN extent must be rejected");

  // 4I. Infinite extent
  map->zoomToExtent(QgsRectangle(200000.0, 450000.0, std::numeric_limits<double>::infinity(), 450100.0));
  QVERIFY2(!LayoutService::isComposedStudioSheet(&proj), "Infinite extent must be rejected");
}

void TestKaHgis::challenge5_isComposed_customNamedLayoutsAndMultipleMaps() {
  QgsProject proj;
  proj.setCrs(QgsCoordinateReferenceSystem(QStringLiteral("EPSG:5186")));

  auto* sa = new QgsVectorLayer(QStringLiteral("Polygon?crs=EPSG:5186"), QStringLiteral("survey_area"), QStringLiteral("memory"));
  QVERIFY(sa->startEditing());
  QgsFeature sf(sa->fields());
  QgsPolylineXY ring;
  ring << QgsPointXY(200000.0, 450000.0) << QgsPointXY(200100.0, 450000.0)
       << QgsPointXY(200100.0, 450100.0) << QgsPointXY(200000.0, 450100.0)
       << QgsPointXY(200000.0, 450000.0);
  sf.setGeometry(QgsGeometry::fromPolygonXY(QgsPolygonXY() << ring));
  QVERIFY(sa->addFeature(sf));
  QVERIFY(sa->commitChanges());
  proj.addMapLayer(sa);

  // 5A: Custom named layout "my_archaeology_sheet"
  QString err;
  QVERIFY(!LayoutService::createBlankSheet(&proj, 297.0, 210.0, QStringLiteral("my_archaeology_sheet"), &err).isEmpty());
  auto* ly = dynamic_cast<QgsPrintLayout*>(proj.layoutManager()->layoutByName(QStringLiteral("my_archaeology_sheet")));
  QVERIFY(ly);

  auto* map = new QgsLayoutItemMap(ly);
  map->setId(QStringLiteral("ka_map"));
  map->attemptSetSceneRect(QRectF(20.0, 20.0, 120.0, 80.0));
  map->setCrs(QgsCoordinateReferenceSystem(QStringLiteral("EPSG:5186")));
  map->setKeepLayerSet(true);
  map->setLayers(QList<QgsMapLayer*>{sa});
  map->zoomToExtent(QgsRectangle(200000.0, 450000.0, 200100.0, 450100.0));
  map->setScale(1000.0);
  ly->addLayoutItem(map);

  QVERIFY2(LayoutService::isComposedStudioSheet(&proj, QStringLiteral("my_archaeology_sheet")),
           "Valid custom-named layout must pass composition check");

  // 5B: Multiple map items where overview map is first and empty, but main map has data
  QVERIFY(!LayoutService::createBlankSheet(&proj, 297.0, 210.0, QStringLiteral("dual_map_sheet"), &err).isEmpty());
  auto* lyDual = dynamic_cast<QgsPrintLayout*>(proj.layoutManager()->layoutByName(QStringLiteral("dual_map_sheet")));
  QVERIFY(lyDual);

  // First map item: overview map without "ka_map" ID, with empty layer
  auto* emptyVl = new QgsVectorLayer(QStringLiteral("Polygon?crs=EPSG:5186"), QStringLiteral("empty_overview"), QStringLiteral("memory"));
  proj.addMapLayer(emptyVl);

  auto* mapOverview = new QgsLayoutItemMap(lyDual);
  mapOverview->setId(QStringLiteral("overview_inset"));
  mapOverview->attemptSetSceneRect(QRectF(10.0, 10.0, 40.0, 30.0));
  mapOverview->setLayers(QList<QgsMapLayer*>{emptyVl});
  mapOverview->zoomToExtent(QgsRectangle(200000.0, 450000.0, 200100.0, 450100.0));
  mapOverview->setScale(5000.0);
  lyDual->addLayoutItem(mapOverview);

  // Second map item: main survey map without "ka_map" ID, with real survey data
  auto* mapMain = new QgsLayoutItemMap(lyDual);
  mapMain->setId(QStringLiteral("main_survey_map"));
  mapMain->attemptSetSceneRect(QRectF(55.0, 10.0, 150.0, 100.0));
  mapMain->setLayers(QList<QgsMapLayer*>{sa});
  mapMain->zoomToExtent(QgsRectangle(200000.0, 450000.0, 200100.0, 450100.0));
  mapMain->setScale(1000.0);
  lyDual->addLayoutItem(mapMain);

  const bool composedDual = LayoutService::isComposedStudioSheet(&proj, QStringLiteral("dual_map_sheet"));
  qDebug() << "[CHALLENGE 5B] Dual-map layout (empty overview first, composed main second) -> isComposed:" << composedDual;
}

void TestKaHgis::challenge6_projectState_featurePlanWithoutActualFeatures() {
  QgsProject proj;
  proj.setCrs(QgsCoordinateReferenceSystem(QStringLiteral("EPSG:5186")));

  // 1. Add valid survey_area
  auto* sa = new QgsVectorLayer(QStringLiteral("Polygon?crs=EPSG:5186"), QStringLiteral("survey_area"), QStringLiteral("memory"));
  sa->setCustomProperty(QStringLiteral("ka_hgis/layer_key"), QStringLiteral("survey_area"));
  QVERIFY(sa->startEditing());
  QgsFeature sf(sa->fields());
  QgsPolylineXY ring;
  ring << QgsPointXY(200000.0, 450000.0) << QgsPointXY(200100.0, 450000.0)
       << QgsPointXY(200100.0, 450100.0) << QgsPointXY(200000.0, 450100.0)
       << QgsPointXY(200000.0, 450000.0);
  sf.setGeometry(QgsGeometry::fromPolygonXY(QgsPolygonXY() << ring));
  QVERIFY(sa->addFeature(sf));
  QVERIFY(sa->commitChanges());
  proj.addMapLayer(sa);

  // 2. Compose user_sheet with survey_area ONLY (no features on user_sheet)
  QString err;
  QVERIFY(!LayoutService::createBlankSheet(&proj, 297.0, 210.0, QStringLiteral("user_sheet"), &err).isEmpty());
  auto* ly = dynamic_cast<QgsPrintLayout*>(proj.layoutManager()->layoutByName(QStringLiteral("user_sheet")));
  QVERIFY(ly);
  auto* map = new QgsLayoutItemMap(ly);
  map->setId(QStringLiteral("ka_map"));
  map->attemptSetSceneRect(QRectF(20.0, 20.0, 120.0, 80.0));
  map->setCrs(QgsCoordinateReferenceSystem(QStringLiteral("EPSG:5186")));
  map->setKeepLayerSet(true);
  map->setLayers(QList<QgsMapLayer*>{sa});
  map->zoomToExtent(QgsRectangle(200000.0, 450000.0, 200100.0, 450100.0));
  map->setScale(1000.0);
  ly->addLayoutItem(map);

  QVERIFY(LayoutService::isComposedStudioSheet(&proj, QStringLiteral("user_sheet")));

  // Sub-probe 6A: fpCount = 0, flCount = 0. Does layout_exists:feature_plan pass?
  QJsonObject st6A = ProjectStateBuilder::fromProject(&proj);
  qDebug() << "[CHALLENGE 6A] With fpCount=0, layout_exists:feature_plan is:" << st6A.value(QStringLiteral("layout_exists:feature_plan")).toBool();
  QVERIFY2(!st6A.value(QStringLiteral("layout_exists:feature_plan")).toBool(),
           "layout_exists:feature_plan must be false when fpCount=0 and flCount=0");

  // Sub-probe 6B: Add feature_poly layer with 1 feature having NULL geometry (geometry-less feature)
  auto* fp = new QgsVectorLayer(QStringLiteral("Polygon?crs=EPSG:5186"), QStringLiteral("feature_poly"), QStringLiteral("memory"));
  fp->setCustomProperty(QStringLiteral("ka_hgis/layer_key"), QStringLiteral("feature_poly"));
  QVERIFY(fp->startEditing());
  QgsFeature fNull(fp->fields());
  fNull.setGeometry(QgsGeometry()); // NULL GEOMETRY
  QVERIFY(fp->addFeature(fNull));
  QVERIFY(fp->commitChanges());
  proj.addMapLayer(fp);

  QCOMPARE(fp->featureCount(), 1);
  QJsonObject st6B = ProjectStateBuilder::fromProject(&proj);
  const bool fpPassedWithNullGeom = st6B.value(QStringLiteral("layout_exists:feature_plan")).toBool();
  qDebug() << "[CHALLENGE 6B] NULL geometry in feature_poly -> fpCount:" << st6B.value(QStringLiteral("feature_poly_count")).toInt()
           << "layout_exists:feature_plan:" << fpPassedWithNullGeom;
}

void TestKaHgis::challenge7_projectState_siteLocationWithoutSurveyArea() {
  QgsProject proj;
  proj.setCrs(QgsCoordinateReferenceSystem(QStringLiteral("EPSG:5186")));

  // No survey_area layer at all
  // Compose user_sheet with dummy feature
  auto* fp = new QgsVectorLayer(QStringLiteral("Polygon?crs=EPSG:5186"), QStringLiteral("feature_poly"), QStringLiteral("memory"));
  fp->setCustomProperty(QStringLiteral("ka_hgis/layer_key"), QStringLiteral("feature_poly"));
  QVERIFY(fp->startEditing());
  QgsFeature ff(fp->fields());
  QgsPolylineXY ring;
  ring << QgsPointXY(200000.0, 450000.0) << QgsPointXY(200100.0, 450000.0)
       << QgsPointXY(200100.0, 450100.0) << QgsPointXY(200000.0, 450100.0)
       << QgsPointXY(200000.0, 450000.0);
  ff.setGeometry(QgsGeometry::fromPolygonXY(QgsPolygonXY() << ring));
  QVERIFY(fp->addFeature(ff));
  QVERIFY(fp->commitChanges());
  proj.addMapLayer(fp);

  QString err;
  QVERIFY(!LayoutService::createBlankSheet(&proj, 297.0, 210.0, QStringLiteral("user_sheet"), &err).isEmpty());
  auto* ly = dynamic_cast<QgsPrintLayout*>(proj.layoutManager()->layoutByName(QStringLiteral("user_sheet")));
  QVERIFY(ly);
  auto* map = new QgsLayoutItemMap(ly);
  map->setId(QStringLiteral("ka_map"));
  map->attemptSetSceneRect(QRectF(20.0, 20.0, 120.0, 80.0));
  map->setCrs(QgsCoordinateReferenceSystem(QStringLiteral("EPSG:5186")));
  map->setKeepLayerSet(true);
  map->setLayers(QList<QgsMapLayer*>{fp});
  map->zoomToExtent(QgsRectangle(200000.0, 450000.0, 200100.0, 450100.0));
  map->setScale(1000.0);
  ly->addLayoutItem(map);

  QVERIFY(LayoutService::isComposedStudioSheet(&proj, QStringLiteral("user_sheet")));

  QJsonObject st7A = ProjectStateBuilder::fromProject(&proj);
  qDebug() << "[CHALLENGE 7A] saCount=0 -> layout_exists:site_location:" << st7A.value(QStringLiteral("layout_exists:site_location")).toBool();
  QVERIFY2(!st7A.value(QStringLiteral("layout_exists:site_location")).toBool(),
           "layout_exists:site_location must be false when survey_area_count is 0");

  // Sub-probe 7B: Add layer named "조사구역" with a POINT feature (not polygon)
  auto* ptSa = new QgsVectorLayer(QStringLiteral("Point?crs=EPSG:5186"), QStringLiteral("조사구역"), QStringLiteral("memory"));
  QVERIFY(ptSa->startEditing());
  QgsFeature ptF(ptSa->fields());
  ptF.setGeometry(QgsGeometry::fromPointXY(QgsPointXY(200050.0, 450050.0)));
  QVERIFY(ptSa->addFeature(ptF));
  QVERIFY(ptSa->commitChanges());
  proj.addMapLayer(ptSa);

  QJsonObject st7B = ProjectStateBuilder::fromProject(&proj);
  const int saCount7B = st7B.value(QStringLiteral("survey_area_count")).toInt();
  const bool siteLoc7B = st7B.value(QStringLiteral("layout_exists:site_location")).toBool();
  qDebug() << "[CHALLENGE 7B] Point feature in '조사구역' -> saCount:" << saCount7B << "layout_exists:site_location:" << siteLoc7B;
}

void TestKaHgis::challenge8_isComposed_autoGeneratedTemplateBypass() {
  QgsProject proj;
  proj.setCrs(QgsCoordinateReferenceSystem(QStringLiteral("EPSG:5186")));

  // Add survey_area with 1 polygon
  auto* sa = new QgsVectorLayer(QStringLiteral("Polygon?crs=EPSG:5186"), QStringLiteral("survey_area"), QStringLiteral("memory"));
  sa->setCustomProperty(QStringLiteral("ka_hgis/layer_key"), QStringLiteral("survey_area"));
  QVERIFY(sa->startEditing());
  QgsFeature sf(sa->fields());
  QgsPolylineXY ring;
  ring << QgsPointXY(200000.0, 450000.0) << QgsPointXY(200100.0, 450000.0)
       << QgsPointXY(200100.0, 450100.0) << QgsPointXY(200000.0, 450100.0)
       << QgsPointXY(200000.0, 450000.0);
  sf.setGeometry(QgsGeometry::fromPolygonXY(QgsPolygonXY() << ring));
  QVERIFY(sa->addFeature(sf));
  QVERIFY(sa->commitChanges());
  proj.addMapLayer(sa);

  // Auto-generate default layouts
  const int generatedCount = LayoutService::ensureDefaultLayouts(&proj);
  qDebug() << "[CHALLENGE 8] Generated default layouts count:" << generatedCount;
  QVERIFY(generatedCount > 0);

  auto* saMapLayout = dynamic_cast<QgsPrintLayout*>(proj.layoutManager()->layoutByName(QStringLiteral("survey_area_map")));
  QVERIFY(saMapLayout);
  qDebug() << "[CHALLENGE 8] survey_area_map custom properties: auto_template ="
           << saMapLayout->customProperty(QStringLiteral("ka_hgis/auto_template")).toBool()
           << "user_composed =" << saMapLayout->customProperty(QStringLiteral("ka_hgis/user_composed")).toBool();

  // Test Worker M1 claim:
  // "LayoutService::isComposedStudioSheet: Rejects uncomposed auto-templates: verifies that if ka_hgis/auto_template is true, ka_hgis/user_composed must be true."
  const bool isComposedSaMap = LayoutService::isComposedStudioSheet(&proj, QStringLiteral("survey_area_map"));
  const bool isComposedSiteLoc = LayoutService::isComposedStudioSheet(&proj, QStringLiteral("site_location"));
  qDebug() << "[CHALLENGE 8] LayoutService::isComposedStudioSheet('survey_area_map') result:" << isComposedSaMap;
  qDebug() << "[CHALLENGE 8] LayoutService::isComposedStudioSheet('site_location') result:" << isComposedSiteLoc;

  // Also check ProjectStateBuilder::fromProject
  const QJsonObject st = ProjectStateBuilder::fromProject(&proj);
  qDebug() << "[CHALLENGE 8] ProjectStateBuilder st.layout_exists:survey_area_map:"
           << st.value(QStringLiteral("layout_exists:survey_area_map")).toBool();
  qDebug() << "[CHALLENGE 8] ProjectStateBuilder st.layout_exists:site_location:"
           << st.value(QStringLiteral("layout_exists:site_location")).toBool();
}

#include "test_checklist.moc"

int main(int argc, char** argv) {
  QgsApplication app(argc, argv, false);
  const QString prefix = qEnvironmentVariable("QGIS_PREFIX_PATH", QFile::exists(QStringLiteral("D:/OSGeo4W/apps/qgis-dev")) ? QStringLiteral("D:/OSGeo4W/apps/qgis-dev") : QStringLiteral("C:/OSGeo4W/apps/qgis-dev"));
  QgsApplication::setPrefixPath(prefix, true);
  QgsApplication::setPluginPath(prefix + QStringLiteral("/plugins"));
  QgsApplication::initQgis();
  TestKaHgis tc;
  const int rc = QTest::qExec(&tc, argc, argv);
  QgsApplication::exitQgis();
  return rc;
}
